### ISSUE TITLE
Support jumphost option in SshOption

### ISSUE THREAD

**Issue by ctakahashi** [dakusui/actionunit#86]
In the [SshOptions](https://github.com/dakusui/actionunit/blob/5.2.x/src/main/java/com/github/dakusui/actionunit/actions/cmd/unix/SshOptions.java) class, it would be useful to be able to add jumphost proxies (more info on [ProxyJump](https://man.openbsd.org/ssh#J)).

By supporting this, it would be simpler to support connecting to remote servers that require jumping through a jumpbox or firewall.

**Comment by dakusui** [comment]
Hi, thank you for feedback and sorry for not noticing your ticket.
Sounds interesting not difficult to make it possible.
However, I have never implemented jumphost and it would be difficult to test the feature.
Any idea to test it?

**Comment by dakusui** [comment]
NOTE: Tested if a composed string seems fine.
